// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace TicTacToe.Api.Migrations
{
    [DbContext(typeof(GameDbContext))]
    partial class GameDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("GameRecord", b =>
                {
                    b.Property<Guid>("GameRecordId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("BoardState")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CurrentPlayer")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool?>("Draw")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("IsOver")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Player1BoxVal")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Player1Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Player2BoxVal")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Player2Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Winner")
                        .HasColumnType("TEXT");

                    b.HasKey("GameRecordId");

                    b.ToTable("GameRecords");
                });
#pragma warning restore 612, 618
        }
    }
}
